name: Build and Publish Crystal

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Crystal
      uses: crystal-lang/install-crystal@v1
      with:
          crystal: latest
          
    - name: Download go-chromecast
      run: |
        wget https://github.com/vishen/go-chromecast/releases/download/v0.3.4/go-chromecast_Linux_x86_64.tar.gz
        tar -xzf go-chromecast_Linux_x86_64.tar.gz
        sudo install ./go-chromecast /usr/bin
        echo $PATH
        
    - name: Build Release
      run: |
        make
        ls build/
        
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/castblock  
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
